attach(projectt_)
library(ggplot2)
library(forecast)
library(tseries)
projectts<-ts(projectt_$MarketCap, start = c(2006,1), frequency = 1)
plot(projectts)
plot(projectts, main= "LSE MarketCap", xlab= "Year", ylab= "MarketCap (£M)")
axis(side = 1, at =seq(2006, 2023, by=1))
acf(projectts)
pacf(projectts)
adf.test(projectts)
projectd<-diff(projectts,1)
plot(projectd)
axis(side = 1, at =seq(2006, 2023, by=1))
acf(projectd)
pacf(projectd)
adf.test(projectd)
auto.arima(projectts)
projectm<-auto.arima(projectts, ic="aic", trace = TRUE)
fit1<-arima(projectd, order = c(0,0,0))
arima(x = projectd, order = c(0,0,0))
pit2<-arima(projectd, order = c(1,1,1))
arima(x = projectd, order = c(1,1,1))
fit3<-arima(projectd, order = c(2,1,1))
arima(x = projectd, order = c(2,1,1))
fit4<-arima(projectd, order = c(2,1,2))
arima(x = projectd, order = c(2,1,2))
summary(fit1)
summary(pit2)
summary(fit3)
summary(fit4)
checkresiduals(pit2)
pit2f<-forecast(pit2, h=10)
print(pit2f)
plot(pit2f)
axis(side = 1, at =seq(2025, 2033, by=1))